language: node_js
node_js:
  - 12
notifications:
  slack: thetablestop:X9qXusai6XjRfiV11LSbdemj
env:
  - VERSION=1.0
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $TRAVIS_REPO_SLUG:$VERSION.$TRAVIS_BUILD_NUMBER .
after_success:
  - docker tag $TRAVIS_REPO_SLUG:$VERSION.$TRAVIS_BUILD_NUMBER $TRAVIS_REPO_SLUG:latest
  - docker push $TRAVIS_REPO_SLUG:$VERSION.$TRAVIS_BUILD_NUMBER
  - docker push $TRAVIS_REPO_SLUG:latest
