language: node_js
node_js:
  - 12
env:
  - VERSION=1.0.$TRAVIS_BUILD_NUMBER
  - REPO_TAG=$TRAVIS_REPO_SLUG:$VERSION
  - REPO_LATEST=$TRAVIS_REPO_SLUG:latest
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $TAG .
after_success:
  - docker tag $TAG $REPO_LATEST
  - docker push $TAG
  - docker push $REPO_LATEST
